services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.1
    command: tunnel run
    container_name: cloudflared
    user: "1001:1001"
    env_file:
      - ./private/cloudflared.env
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    networks:
      - public
      - internet
    restart: unless-stopped

  caddy-public:
    image: caddy:2.10
    container_name: caddy-public
    volumes:
      - ./config/caddy-public/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-public/data:/data
      - ./data/caddy-public/config:/config
    networks:
      - public
    restart: unless-stopped

  caddy-private:
    image: caddy:2.10
    container_name: caddy-private
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/caddy-private/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-private/data:/data
      - ./data/caddy-private/config:/config
    networks:
      - private
    restart: unless-stopped

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dockge:/app/data
      - ../:/app/stacks
    environment:
      - DOCKGE_STACKS_DIR=/app/stacks
      - DOCKGE_BASE_URL=/dockge
    networks:
      - private

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true
  internet:
    name: internet
    external: true
