apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
type: Opaque
data:
  groq-api-key: Z3NrXzNyVEpJS1N4UHpHT3ltY2VGVmRNV0dkeWJzRllJZmRrM3o5Y1BFYmRzTkZqNGxxako0Tw==
  tavily-api-key: dHZseS1kZXYtaFVUeWtySVBaTUoxRjZUZU1NN3RvNEJxeFlBRUpjYm0=
  jina-api-key: amluYV8wODExZTAzYWFlZjk0MmQ0ODZhMTNhYWU5MDEyNGM0MlpTMlYxalExVXlLLUZvclc3eFQyS2RfV0Z3N0Nv